### ISSUE TITLE
WordPress.org » This plugin provides 4 blocks » 4 × "Pronamic Pay"

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/wp-pronamic-pay#185]
https://wordpress.org/plugins/pronamic-ideal/

<img width="677" alt="Schermafbeelding 2021-08-17 om 11 24 45" src="https://user-images.githubusercontent.com/869674/129700545-5ac837cf-b729-415f-bfbc-093a95d75f02.png">

Why do we see a "Pronamic Pay" block 4 times on https://wordpress.org/plugins/pronamic-ideal/?

**Comment by rvdsteege** [comment]
Because we're registering 4 blocks (1 core and 3 fundraising).

Adding the titles might fix the displayed block names (we'll have to wait and see for next plugin update):

- https://github.com/pronamic/wp-pay-core/commit/1070a563cd0569609ca6d40a7b79b15a41193abe
- https://github.com/wp-pay/fundraising/commit/3190282a6ac593778db916f92cfb3cf3e12fce00

**Comment by remcotolsma** [comment]
@rvdsteege Was this just a guess, or did you read somewhere that this should fix it?

I searched for the "This plugin provides %d blocks." translation on https://translate.wordpress.org/ and found this:
https://translate.wordpress.org/projects/meta/plugins-v3/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=7524862&filters%5Btranslation_id%5D=64565995

References: https://meta.trac.wordpress.org/browser/sites/trunk/wordpress.org/public_html/wp-content/themes/pub/wporg-plugins/template-parts/section-blocks.php?marks=41#L41.

I think finding the blocks is handled in https://github.com/WordPress/wordpress.org/blob/3d3cc7df3b9be7a58ab369218b7a7a4eff845547/wordpress.org/public_html/wp-content/plugins/plugin-directory/cli/class-import .php#L733-L797.

It seems that the titles for blocks registered via PHP are not being read?

Is a `block.json` file for each block the way forward?

For WooCommerce I think it's read from the `registerBlockType` call from for example:
https://plugins.trac.wordpress.org/browser/woocommerce/tags/5.6.0/packages/woocommerce-blocks/build/price-filter.js

**Comment by rvdsteege** [comment]
Adding the titles was a wild guess, but indeed did not resolve the issue.

**Comment by remcotolsma** [comment]
@rvdsteege I think we have to change the build script, store `block.json` for each block in https://github.com/pronamic/wp-pronamic-pay-fundraising/tree/develop/js/dist.

- `js/dist/blocks/fundraising-progress-circle/block.json` → Fundraising Progress Circle → https://github.com/pronamic/wp-pronamic-pay-fundraising/blob/develop/js/src/progress-circle/block.json
- `js/dist/blocks/fundraising-progress-bar/block.json` → Fundraising Progress Bar → https://github.com/pronamic/wp-pronamic-pay-fundraising/blob/develop/js/src/progress-bar/block.json
- `js/dist/blocks/fundraising-progress-text/block.json` → Fundraising Progress → https://github.com/pronamic/wp-pronamic-pay-fundraising/blob/develop/js/src/progress-text/block.json

Same way like in https://plugins.trac.wordpress.org/browser/gutenberg/tags/11.5.1/build/block-library/blocks#calendar.

And start using `register_block_type_from_metadata`?
https://github.com/WordPress/gutenberg/search?q=register_block_type_from_metadata

Same for the `pronamic-pay/payment-form` → "Payment Form" block in https://github.com/pronamic/wp-pay-core/search?q=register_block_type.

**Comment by rvdsteege** [comment]
Fundraising `block.json` added and started using `register_block_type_from_metadata()` (requires WordPress 5.5 or higher):
- https://github.com/pronamic/wp-pronamic-pay-fundraising/commit/d158f446293b70c2f9d5ca2010ddbe01e3722098

Issue left open to update payment form `block.json`.

**Comment by rvdsteege** [comment]
Seems that if there are `block.json` files, `*.js` and `*.php` files are not being processed by the wordpress.org plugin directory:

- https://github.com/WordPress/wordpress.org/blob/3d3cc7df3b9be7a58ab369218b7a7a4eff845547/wordpress.org/public_html/wp-content/plugins/plugin-directory/cli/class-import.php#L593-L627

That is why only the fundraising blocks got listed now in the plugin directory. Added `block.json` for the `pronamic-pay/payment-form` block in https://github.com/pronamic/wp-pay-core/commit/0def70499e870a12de361c919f44b27992ecbdc3.
